- packages/themes/package.json
- packages/themes/src/loadTheme.ts
VS Code uses JSON5 to parse themes, which is why I can have comments in my theme file. For Shiki to work with all themes, this package should use JSON5 too . Thanks!
> Use json5 for full theme compat

- packages/languages/src/lang.ts
This moves the `path.resolve()` in place so that static analysis tools such as webpack and node-file-trace can determine that the assets in `../data/grammars` should be bundled.
Fixes https://twitter.com/browniefed/status/1288502416732614656
> [languages] Move path.resolve() for better static analysis

- packages/shiki/src/renderer.ts
Conf. issue <https://github.com/octref/shiki/issues/26>
> escapeHtml bug fix

- README.md
It was inevitable that a LaTeX renderer would happen, right?
Well, I [needed](https://github.com/leafac/yocto-cfa) better syntax highlighting than I was getting with Pygments, so here we are.
Thanks for putting Shiki together. It’s the best in the business!
> Add Shiki LaTeX to list of related projects

- packages/shiki/src/themedTokenizer.ts
TypeDoc@future is using Shiki now for highlighting, and while profiling I noticed that >50% of the runtime in a moderately sized project was spent highlighting code comments. ~60% of this time was spent in node internals, which I deduced was the `substring` calls here.
Unfortunately, due to the existing API contract requiring that the same string be included several times, it isn't possible to completely eliminate this overhead... but I was able to reduce the runtime by ~20% by making these changes. There is still lots of room for improvement. I think the runtime can be cut in half if less information is returned (I don't need all that this gives... maybe I should just be using vscode-textmate directly)
> perf: Avoid some unnecessary string copies

- packages/shiki/src/highlighter.ts
- packages/shiki/src/themedTokenizer.ts
As alluded to in #51, there are still lots of string copies that aren't necessarily required when tokenizing due to including the explanation for each token's color. This adds an option which can be used to disable the explanation generation if not required.
Since this builds on the changes in #51, it is also included in this PR.
> Add an option to skip generating the explanation text

- CHANGELOG.md
- packages/themes/README.md
- packages/themes/data/slack-theme-dark-mode.json
- packages/themes/data/slack-theme-ochin.json
- packages/themes/src/theme.ts
- scripts/pullThemesFromGitHub.js
> feat: slack themes

- README.md
Hi @octref ! 👋
I have been considering different highlighting options (also Prism.js with `react-syntax-highlighter`), and stumbled upon your project through Orta (who used it for the [`shiki-twoslash`](https://www.npmjs.com/package/shiki-twoslash) package for the TypeScript website)
One thing that I was looking for when going through this repo and also the docs website was an interactive demo.
I've set one up on CodeSandbox (with Next.js). It is currently a frozen sandbox (so that I remember to not accidentally make changes to it), but of course happy to have you fork it so that you control the sandbox.
What are your thoughts?
> Add CodeSandbox interactive demo (with Next.js)

- README.md
Since in `index.ts` we don't export any default module,
https://github.com/shikijs/shiki/blob/58cb92cd9427a97d5b4f89e3cec8e12290fcb793/packages/shiki/src/index.ts#L1-L6
it would raise an error like this, if we use `import shiki from 'shiki'` syntax.
```
The requested module 'file:///<some-path>/node_modules/shiki/dist/index.js' does not provide an export named 'default'
```
I think it's better to add destructure way to import `shiki`.
> fix(readme): add destructure import example

- scripts/pullGrammarsFromGitHub.js
The repository no longer exists.
Also, the Fortran grammar was removed from the repo in https://github.com/shikijs/shiki/commit/6ff3df2329122d3bc805cffc6e362c4ed6c13ecc.
> Remove Fortran grammar

- scripts/pullGrammarsFromGitHub.js
If we fail to download a certain grammar, we still want to continue with the remaining ones.
> Handle errors in pullGrammarsFromGitHub.js

- packages/shiki/src/index.ts
Been moving the TypeScript website over, while this isn't essential, I have been using it a lot in my custom shiki renderers to be consistent with the default renderer
> Expose the HtmlRendererOptions

- packages/shiki/src/loader.ts
We have a bunch of checks for nullability in this code, but we're missing the one for colors being undefined.
> Allow colors to be undefined on a theme

- lerna.json
- packages/shiki/package.json
- packages/shiki/src/loader.ts
By default jest include jsdom, which adds both document and window - but does not include fetch. By adding fetch to the check we can run in Jest without additional config on end users setting `"testEnvironment": "node"`.
> Expand browser check to include 'fetch'

- packages/shiki/src/languages.ts
- scripts/updateLangSrc.js
Many LaTeX source code have the extenstion `.tex`, so I make `tex` an alias to `latex`.
> feat: add 'tex' as an alias of latex

- packages/shiki/src/highlighter.ts
The calls to `loadThemes` and `loadLanguages` used to occur before these options were applied, which meant that if you didn't have themes/languages in their default paths, `getHighlighter` would always fail.
> Update themesPath and languagesPath earlier

- packages/shiki/src/highlighter.ts
`setTheme` can be an expensive operation because it parses the raw theme
every time it's called:
https://github.com/microsoft/vscode-textmate/blob/9e3c5941668cbfcee5095eaec0e58090fda8f316/src/main.ts#L93-L95
In https://github.com/banga/git-split-diffs/, I invoke
`codeToThemedTokens` many times, one line at a time, so the cost of
`setTheme` adds up. In my local profiling, this was taking about 25% of
the time spent in `codeToThemedTokens`. I realize this is probably not
the intended way to use this function, but there isn't an easy
alternative for syntax highlighting individual lines in a diff.
Before
After
> Don't call `setTheme` if `_theme` hasn't changed

- packages/site/mono.md
Per the title. Thanks for all your amazing work on this library @octref, it's really a wonderful project 🙂 🙌
> fix: small typo in mono.md (readfileSync should be readFileSync)

- packages/shiki/src/highlighter.ts
- packages/shiki/src/types.ts
`getTheme` supports passing an `undefined` to grab the default but the types doesn't cover that case, this makes the param optional to account for that.
> Allow dropping the theme option in the highlighter's getTheme interface

- docs/languages.md
- packages/shiki/languages/prisma.tmLanguage.json
- packages/shiki/samples/prisma.sample
- packages/shiki/src/languages.ts
- scripts/grammarSources.ts
Add support for [Prisma's](https://github.com/prisma/prisma) datamodel syntax.
e.g.
```prisma
datasource db {
provider = "postgresql"
url      = env("DATABASE_URL")
}
generator client {
provider = "prisma-client-js"
}
model Post {
id        Int         @default(autoincrement()) @id
content   String?
published Boolean     @default(false)
author    User?       @relation(fields: [authorId], references: [id])
authorId  Int?
}
model User {
id    Int     @default(autoincrement()) @id
email String  @unique
name  String?
role  Role    @default(USER)
posts Post[]
}
enum Role {
USER
ADMIN
}
```
> feat: add prisma language

- packages/shiki/src/loader.ts
- packages/shiki/tsconfig.json
- tsconfig.json
Resolves #188 
These changes aim to make `shiki` working in web workers :)
Side note : `WebWorker` is needed in `tsconfig.json` to make `WorkerGlobalScope` available on `self`.
> feat: support web workers

- packages/shiki/src/languages.ts
For some reason `vue-html` isn't registered in languages, which causes `<template>` blocks in Vue files not being properly highlighted.
Adding this also enables highlighting a piece of Vue template directly (without having to nest it inside `<template>` as in SFCs).
> Fix Vue template highlighting

- docs/languages.md
- packages/shiki/languages/fish.tmLanguage.json
- packages/shiki/samples/fish.sample
- packages/shiki/src/languages.ts
- scripts/grammarSources.ts
This PR adds support for [fish shell](https://fishshell.com/) language.
```fish
function fish_prompt
set -l user_char '►'
if fish_is_root_user
set user_char '#'
end
echo (set_color yellow)$PWD (set_color purple)$user_char
end
```
> feat: add fish shell language

- packages/shiki/src/stackElementMetadata.ts
This makes it possible to use Shiki with projects that set the "isolatedModules" flag for improved compiler performance.
Closes #172
> Remove "const" from publicly exported enums

- packages/shiki/src/__tests__/__snapshots__/cssVars.test.ts.snap
- packages/shiki/src/highlighter.ts
Resolves #214 
While testing the latest changes in the Astro repo I uncovered a small bug in #212 where the `foreground` and `background` styles were not being applied. @tbeseda ran into the same in #214.
The fix is that foreground and background are managed separately, outside of the color map. This PR adds these two properties to the "fix" step. Tests also updated.
> [css-variables] fix theme fg & bg

- README.md
Hi @octref . We've implement a util based on shiki. It converts shiki tokenizer result to chalk calls, which enables syntax highlighting for outputing instruction codes in terminals.
I'm wondering if it's possible to add the tool to `Seen` part, thanks~
> Add CodeChalk to `Seen` section

- packages/shiki/package.json
TypeDoc 0.22.3:
```
Debug: Loading Shiki took 1956ms
Debug: HTML rendering took 2243ms
```
Shiki makes up 87% of the time TypeDoc takes to render, I'm hoping #222 has helped the situation.
> Bump Shiki version

- packages/renderer-svg/LICENSE
- packages/shiki/LICENSE
- packages/vuepress-plugin/LICENSE
Howdy!
I noticed the packages in this monorepo were missing License files. This causes problems with many automated tools as your License file will not be included in the distributed rpm bundle. Thought I'd shoot you a PR to fix this 😉
> Add licensing information to packages

- packages/shiki/src/__tests__/__snapshots__/multiFontStyle.test.ts.snap
- packages/shiki/src/__tests__/multiFontStyle.test.ts
- packages/shiki/src/renderer.ts
`FontStyle` is bitwise and themes can set multiple font styles simultaneously (e.g. https://github.com/theacodes/witchhazel/blob/5dc744fb0fb7210be1ccacc5863a5768644a8380/witchhazelhypercolor.tmTheme#L139-L151).
Tested locally with a converted version of Witch Hazel Hypercolor (as linked above).
> Handle token colors with multiple font styles

- packages/shiki/src/__tests__/background.test.ts
- packages/shiki/src/__tests__/comprehensive.test.ts
- packages/shiki/src/__tests__/cssVars.test.ts
- packages/shiki/src/__tests__/multiFontStyle.test.ts
- packages/shiki/src/__tests__/simple.test.ts
There's no need for the tests to load things that they don't need, or repeatedly load the same grammars and themes again and again...
```
Tests:       160 passed, 160 total
Snapshots:   7 passed, 7 total
Time:        10.297 s, estimated 28 s
```
> refactor: Make tests take less than half as long to run

- packages/shiki/package.json
So that the fix to gh-219 gets released. @Gerrit0 recommended I do this.
- [ N/A ] Add a test if possible
- [ X ] Format all commit messages with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
> chore: bump shiki version number

- scripts/grammarSources.ts
We updated the Astro org name which means we now have a new URL. I ran ` yarn update:grammars ` and confirmed no other changes were needed!
> docs: update astro grammar url

- packages/shiki/package.json
Release includes:
- Updated grammars / themes
- fix: Update oniguruma to version used by VSCode 
- fix typo: grammer -> grammar (technically a breaking change, but it doesn't look like anyone uses it, so I left this as a patch release)
> chore: Bump Shiki version to 0.9.13

- README.md
- packages/shiki/README.md
- packages/shiki/src/__tests__/__snapshots__/deprecatedOverloads.test.ts.snap
- packages/shiki/src/__tests__/background.test.ts
- packages/shiki/src/__tests__/comprehensive.test.ts
- packages/shiki/src/__tests__/cssVars.test.ts
- packages/shiki/src/__tests__/custom-language/customLanguage.test.ts
- packages/shiki/src/__tests__/deprecatedOverloads.test.ts
- packages/shiki/src/__tests__/multiFontStyle.test.ts
- packages/shiki/src/__tests__/simple.test.ts
- packages/shiki/src/highlighter.ts
- packages/shiki/src/types.ts
- packages/site/gen-custom-theme.js
- packages/site/gen-index.js
- packages/site/gen-mono.js
- packages/site/gen-palenight.js
- packages/site/gen-wenyan.js
- packages/site/index.md
- packages/vuepress-plugin/index.js
Deprecate the `codeToHtml(code, lang?, theme?)` overload in favor of `codeToHtml(code, options?)`. For the discussion about this PR, please see #260.
> Deprecate the codeToHtml(code, lang?, theme?) overload in favor of codeToHtml(code, options?)

- docs/themes.md
- packages/shiki/src/themes.ts
- packages/shiki/themes/minimus.json
- scripts/themeSources.ts
Updating the name of the "minimus" theme. It was previously added with the wrong name ("spaceinvadev").
> fix minimus theme name

- docs/languages.md
- packages/shiki/languages/codeql.tmLanguage.json
- packages/shiki/samples/codeql.sample
- packages/shiki/src/languages.ts
- scripts/grammarSources.ts
*[CodeQL](https://codeql.github.com/) is the analysis engine used by developers to automate security checks, and by security researchers to perform variant analysis.*
*In CodeQL, code is treated like data. Security vulnerabilities, bugs, and other errors are modeled as queries that can be executed against databases extracted from code. You can run the standard CodeQL queries, written by GitHub researchers and community contributors, or write your own to use in custom analyses. Queries that find potential bugs highlight the result directly in the source file.* 
See [documentation](https://codeql.github.com/docs/codeql-overview/about-codeql/)
> feat: Add support for CodeQL language

- docs/languages.md
- packages/shiki/languages/cue.tmLanguage.json
- packages/shiki/samples/cue.sample
- packages/shiki/src/languages.ts
- scripts/grammarSources.ts
Signed-off-by: Tony Worm <tony@hofstadter.io>
The adding grammar doc looks to be slightly out of date. Had to edit two files.
A lot of other files were updated when I ran `yarn update`, but those are not included.
---
- https://cuelang.org 
- https://github.com/cue-lang/cue
- https://cuetorials.com
> add files for CUE

- packages/shiki/src/__tests__/__snapshots__/lineOptions.test.ts.snap
- packages/shiki/src/__tests__/lineOptions.test.ts
- packages/shiki/src/highlighter.ts
- packages/shiki/src/renderer.ts
- packages/shiki/src/types.ts
- packages/shiki/src/utils.ts
In this PR, I'm implementing support for adding custom CSS classes to specific lines. This is picking up the work that @dceddia started in #83.
The `codeToHtml` now accepts an optional `options` object with an optional `highlightedLines` property:
```ts
function codeToHtml(
code: string,
lang?: StringLiteralUnion<Lang>,
theme?: StringLiteralUnion<Theme>,
options?: HtmlOptions
): string {
// ...
}
export interface HtmlOptions {
highlightedLines?: HighlightedLines
}
```
Highlighted lines can be specified one by one, or as a range of lines:
```ts
type LineNumber = number
type LineNumberRange = [fromLine: number, toLine: number]
export type HighlightedLines = (LineNumber | LineNumberRange)[]
```
Here's an example usage that would highlight lines 1, 3, 4, 5, 6, and 8:
```js
const code = ` …
```
> Implement support for adding custom CSS classes to specific lines

- scripts/grammarSources.ts
> fix: updated astro grammar source

- packages/shiki/src/__tests__/__snapshots__/lineOptions.test.ts.snap
- packages/shiki/src/__tests__/lineOptions.test.ts
- packages/shiki/src/highlighter.ts
Currently it isn't possible to highlight lines in `txt` code blocks because the entire code is being treated as a single line. This changes makes the highlighter respect line breaks.
> Split plaintext code into lines

- docs/languages.md
- packages/shiki/languages/marko.tmLanguage.json
- packages/shiki/samples/Marko.sample
- packages/shiki/src/languages.ts
- scripts/grammarSources.ts
Added Marko language from eBay's Marko web framework
e.g.
```marko
<await(slowPromise) timeout=5000>
<@then>Done</@then>
<@catch|err|>
<if(err.name === "TimeoutError")>
Took too long to fetch the data!
</if>
<else>
Promise failed with ${err.message}.
</else>
</@catch>
</await>
```
> feat: add marko language

- docs/languages.md
- packages/shiki/languages/zenscript.tmLanguage.json
- packages/shiki/samples/zenscript.sample
- packages/shiki/src/languages.ts
- scripts/grammarSources.ts
ZenScript is a scripting language for Java. It is primarily used by [CraftTweaker](https://github.com/CraftTweaker/CraftTweaker), which is a Minecraft mod that allows users to change many aspects of the game using scripts.
> Add ZenScript support

- packages/vuepress-plugin/index.js
Allow additional language registration through `option.additionalLangs`, which is an array of [`ILanguageRegistration`](https://github.com/shikijs/shiki/blob/ebb3f1f5da4bbc130b48d0a15ff60973b5d0ce82/packages/shiki/src/types.ts#L117) objects.
> [Vuepress plugin] Support additional language registration

- docs/languages.md
- packages/shiki/languages/liquid.tmLanguage.json
- packages/shiki/samples/liquid.sample
- packages/shiki/src/languages.ts
- scripts/grammarSources.ts
---
Your [contributing guidelines](https://github.com/shikijs/shiki/blob/main/.github/CONTRIBUTING.md#coding-conventions) suggest using the "lang" commit scope for these commits/PRs however recent PRs instead seem to follow "feat: add [lang] lang" convention so I've continued with that, please let me know if you'd prefer I change it.
> feat: add liquid lang

- docs/languages.md
- packages/shiki/languages/clarity.tmLanguage.json
- packages/shiki/samples/clarity.sample
- packages/shiki/src/languages.ts
- scripts/grammarSources.ts
- ~~Add a test if possible~~
Note: There is an earlier PR adding this: https://github.com/shikijs/shiki/pull/48
It was closed saying only top 50 languages were being added at that time, but based on recent PRs I assume that's no longer the case
> feat: add Clarity lang

- packages/shiki/src/loader.ts
`fetch` has become available in the `global` in Node since version 18. The `isBrowser` check in Shiki looks like this:
```js
const isWebWorker = typeof self !== 'undefined' && typeof self.WorkerGlobalScope !== 'undefined';
const isBrowser = isWebWorker ||
(typeof window !== 'undefined' &&
typeof window.document !== 'undefined' &&
typeof fetch !== 'undefined');
```
`typeof fetch !== 'undefined'` will now be always true starting with Node 18, which means Shiki will use `fetch` unconditionally.
This PR fixes the issue by only setting `isBrowser` to `true` if it is executing in a web worker, or if the code is most likely not executing in Node. The reason why checking for the presence of `window` and `window.document` is not enough is because users may be using `JSDOM` or similar and creating …
> fix isBrowser check

- packages/shiki/src/__tests__/__mocks__/fs.ts
- packages/shiki/src/__tests__/fetchtheme.test.ts
- packages/shiki/src/__tests__/utils.test.ts
- packages/shiki/src/loader.ts
- packages/shiki/src/utils.ts
Combo bug report/pull request here - please review carefully when you can, I definitely may have missed things, and I've only examined this fix in the context of using it in a VSCode plugin, and in the node REPL - I haven't tested it in browser etc. I've written some extra tests too. Note though that I'm assuming loadTheme is only meant to work with absolute URLs - see my extra notes at the bottom of this post. Apologies for the wall of text!
I was using `shiki` to load vscode themes using absolute pargs from my local file-system, and if I called `shiki.loadTheme` (i.e. `loader.fetchTheme`) with an absolute path for a theme with an `'include'` property referring to a second theme, it would try to load the second theme using only the last directory in the path of the first theme, combined …
> Fix: `fetchTheme` theme 'include' directory joining for absolute paths

- packages/shiki/languages/hcl.tmLanguage.json
- packages/shiki/samples/hcl.sample
- packages/shiki/src/languages.ts
- scripts/grammarSources.ts
This PR updates the source for the HCL language grammar to the [HashiCorp syntax repository](https://github.com/hashicorp/syntax) and adds an example file for HCL.
We recently released an official [HCL extension](https://github.com/hashicorp/vscode-hcl/) for VS Code. This updated extension contains the latest grammar with updates for HCL v2. Since the grammars for HCL and Terraform are very similar, we decided to keep everything in a [central syntax repository](https://github.com/hashicorp/syntax) and download the grammars on extension release.
---
> feat: update HCL grammar source

- packages/shiki/rollup.config.mjs
- packages/shiki/src/loader.ts
@orta Unfortunately I introduced a bug with/for 0.12.0 [that breaks browser environments](https://github.com/shikijs/shiki/compare/main...muenzpraeger:shiki:rw/loader-fix?expand=1#diff-e34964bc43c8f1c17b359513e4ef22495a5ac8db4d44391c1fbbbc6859d13787L49).
While I was there I at least fixed the Rollup builds (back to the state of bundling like 0.10.1), so that unpkg and jsDelivr are working agin. This fixes #338 and fixes #365
> fix: corrected introduced loader issue / fixes jsDelivr and unpkg bundles

- docs/languages.md
- packages/shiki/languages/ara.tmLanguage.json
- packages/shiki/samples/ara.sample
- packages/shiki/src/languages.ts
- scripts/grammarSources.ts
Hi there 👋,
This PR adds support for the `ara` language (https://ara-lang.io/).
Merging this into shiki would allow us and others to have first-party support for the `ara` language code blocks on the documentation website.
Thank you for considering.
---
> feat: add `ara` language

- README.md
Thanks for creating such a beautiful syntax highlighter!
I try using an example code of customizing code block rendering on README, but it doesn't work. It seems only [able to access renderToHTML from `shiki` global object](https://github.com/shikijs/shiki/blob/main/packages/shiki/src/index.ts#L9), [not a highlighter](https://github.com/shikijs/shiki/blob/main/packages/shiki/src/highlighter.ts#L204-L217). I fixed the doc.
> doc: Fix a way to access `renderToHTML`

- docs/languages.md
- packages/shiki/languages/kusto.tmLanguage.json
- packages/shiki/samples/kusto.sample
- packages/shiki/src/languages.ts
- scripts/grammarSources.ts
This add grammar for Kusto ([link](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/))
I added the alias `kql` but I'm not 100% sure what effect aliases have so just making a note here.
> feat: add kusto grammar

- README.md
It shouldn't have an apostrophe.
> docs: fix grammar of "grammar's"

- packages/shiki/languages/lua.tmLanguage.json
- packages/shiki/languages/marko.tmLanguage.json
- packages/shiki/languages/mdx.tmLanguage.json
- packages/shiki/src/languages.ts
- scripts/grammarSources.ts
This PR fixes broken links to marko, mdx, and vue. They changed their repository layouts, leading to broken links.
The changes to `mdx` specifically are very impactful, as the link has been broken for some time.
> fix: marko, mdx, vue

- docs/languages.md
- packages/shiki/languages/reg.tmLanguage.json
- packages/shiki/samples/reg.sample
- packages/shiki/src/languages.ts
- scripts/grammarSources.ts
This adds the grammar for Windows Registry Editor syntax
closes #450
> feat: add reg grammar

- packages/shiki/src/types.ts
It's suffering without autocompletion when trying to use built-in themes. But I noticed that the code has already attempted to provide it but it stoped working on `TypeScript version >= 4.7.4`.
I've tested different approaches, here's the [playground demo](https://www.typescriptlang.org/play?#code/PTAEFsHsDcFNQC4At4GMCuAnAzpTjJEVRsFMBLAOwHMAaUAQ0oBNQAHTWbbQGAZQBhALIARUAGpQ5UIFgGBIQRcEjdHNSRwbADawE5SJQCwAKGMhQARgB0oAKq7N5BAE9ETtvADujpKAcLMDJqgAN4AvgBcoML6AORKHngA1sawAB5seErO7qAAymRU1AAyjrABmjaUepTmADwAKqBpCizYtvQ2oAC8JAU0AHzdoI0APqAAFJ0AZCGhAJTGapSkiIrmkfkUNCX+gZXVdTEAgkcxoGMxAEKXMYM9MTHGT0ZmAEzWduR+Ltme3k3gRwuKj+ABmDFQsEi0S4oASmGSRhBZXBkNAADlIMhCrMUulMq4cptCjsynsqvpXg0mqkWsw2jYOkNSFtqHdhucJtMMVikIUFkYlisFKRXhs+sVSuV9pTasdTpyrjd2Q9nqYwABmayk8qEqFRSCw+GIoVZRQayLys4Xa7WiYsnEzMJzIYPIA), and …
> fix(type): `theme` field autocompletion

- packages/shiki/src/global.d.ts
- packages/shiki/src/loader.ts
I didn't add any automated test, but I checked that after running `pnpm build`, there was no mention of `Window` in the `index.d.ts` file:
I didn't add any test because:
-  this test would require to be ran **after** `pnpm build`
- if we wanted to write to test to ensure that we aren't poisoning the global scope, we need to do something like "is Response, or Window, etc., in the generated code?" But `Response` is used so we cannot use that, and other may be used in the future. So I don't know which test we could write that could be future proof for this.
I couldn't use just `declare var fetch` and others, because we need to add to the global scope `Window` and others as they are used by shiki's node_modules (and so when running tests locally, we need them, see …
> fix: avoid poisoning global scope

- docs/languages.md
- packages/shiki/languages/wolfram.tmLanguage.json
- packages/shiki/samples/wolfram.sample
- packages/shiki/src/languages.ts
- scripts/grammarSources.ts
This adds the Wolfram grammar from [the official source](https://github.com/WolframResearch/vscode-wolfram).
> feat: add wolfram grammar

- docs/themes.md
- packages/shiki/src/__tests__/__snapshots__/ansi.test.ts.snap
- packages/shiki/src/__tests__/ansi.test.ts
- packages/shiki/src/ansiThemedTokenizer.ts
- packages/shiki/src/highlighter.ts
- packages/shiki/themes/css-variables.json
I realized while integrating the recent ANSI support into Nextra that Nextra uses the css-variables functionality which was not working with ANSI colors. I've updated the default color replacements and css-variables theme to support ANSI colors and updated the ANSI tokenizer to use a separate `-dim` variable for dimmed colors since we can no longer add opacity ourselves.
> Add support for the css-variables theme to ansi rendering

- docs/languages.md
- packages/shiki/languages/beancount.tmLanguage.json
- packages/shiki/samples/beancount.sample
- packages/shiki/src/languages.ts
- scripts/grammarSources.ts
This adds support for the [beancount](https://beancount.github.io/docs/index.html) syntax
> feat: add beancount grammar

- docs/languages.md
- packages/shiki/languages/vyper.tmLanguage.json
- packages/shiki/samples/vyper.sample
- packages/shiki/src/languages.ts
- scripts/grammarSources.ts
This adds the vyper grammar found [here](https://github.com/tintinweb/vscode-vyper).
I'm not personally familiar with this language, but it looks like that it uses a `.vy` extension. Should that be added somewhere?
> feat: add vyper grammar

- docs/languages.md
- packages/shiki/languages/cypher.tmLanguage.json
- packages/shiki/samples/cypher.sample
- packages/shiki/src/languages.ts
- scripts/grammarSources.ts
This adds the Cypher query language grammar ([source](https://github.com/adam-cowley/neo4j-vscode))
The grammar mentions `"fileTypes": ["cql", "cyp", "cypher"],`. Should these be added somewhere as aliases perhaps?
> feat: add cypher grammar

- docs/languages.md
- packages/shiki/languages/hjson.tmLanguage.json
- packages/shiki/samples/hjson.sample
- packages/shiki/src/languages.ts
- scripts/grammarSources.ts
> feat: add hjson

- README.md
The browser based example will download 162 JSON files if not specified, which leads to 10+ second loading times. I'm pretty sure I was also getting rate limited by unpkg as well because I was getting random broken loads. 
Might be worth making the languages opt-in when working in the browser, but at least this PR will make the initial demo work smoothly.
re: https://github.com/shikijs/shiki/issues/306
> Specify langs in browser based example

- docs/languages.md
- packages/shiki/languages/glimmer-js.tmLanguage.json
- packages/shiki/languages/glimmer-ts.tmLanguage.json
- packages/shiki/samples/gjs.sample
- packages/shiki/samples/gts.sample
- packages/shiki/src/languages.ts
- scripts/grammarSources.ts
Adds support for `.gjs` and `.gts` file formats. Glimmer `<template>` tag components are the new format which power Ember.js. References:
- RFC: https://rfcs.emberjs.com/id/0779-first-class-component-templates
- Component implementation: https://github.com/ember-template-imports/ember-template-imports
- VS Code language definitions: https://github.com/chiragpat/vscode-glimmer
Local test:
> feat: add glimmer js/ts language

- docs/languages.md
- packages/shiki/languages/narrat.tmLanguage.json
- packages/shiki/samples/narrat.sample
- packages/shiki/src/languages.ts
- scripts/grammarSources.ts
> feat: add narrat grammar

- docs/languages.md
- packages/shiki/languages/splunk.tmLanguage.json
- packages/shiki/samples/splunk.sample
- packages/shiki/src/languages.ts
- scripts/grammarSources.ts
This adds support for the [splunk search processing language](https://www.splunk.com/) syntax
> feat: add splunk grammar

- packages/shiki/src/global.d.ts
- packages/shiki/src/loader.ts
- packages/shiki/tsconfig.json
TypeDoc doesn't have "DOM" in the lib, so doesn't have a global `Response` interface like DOM types do. The changes in #384 (cc @orta) broke me because it references that type now. This moves the interface into loader.ts so that it gets bundled in the declaration file output.
> fix: Compiler errors in Node

- packages/shiki/src/languages.ts
- scripts/grammarSources.ts
add file aliases `kt` and `kts` for kotlin
> fix: add 'kt' and 'kts' alias for kotlin

- docs/languages.md
- packages/shiki/src/languages.ts
- scripts/grammarSources.ts
> fix: alias `c++` to `cpp`

- docs/languages.md
- packages/shiki/languages/nushell.tmLanguage.json
- packages/shiki/samples/nushell.sample
- packages/shiki/src/languages.ts
- scripts/grammarSources.ts
Add grammar for [Nushell](https://github.com/nushell/nushell)
> feat: Add `nushell` grammar

- docs/.vitepress/config.ts
- docs/guide/install.md
- docs/packages/markdown-it.md
- packages/markdown-it/README.md
markdown-it seems to go by the capitalization/spelling of `markdown-it` in all places that I can find. I feel it is best to respect their branding!
N/A
N/A
> docs: Markdown It -> markdown-it

- docs/.vitepress/store/playground.ts
- docs/guide/transformers.md
- packages/core/src/code-to-hast.ts
- packages/core/src/types.ts
- packages/core/src/utils.ts
- packages/rehype/src/core.ts
- packages/transformers/src/shared/highlight-word.ts
- packages/transformers/src/transformers/compact-line-options.ts
- packages/transformers/src/transformers/notation-highlight-word.ts
- packages/transformers/src/transformers/notation-map.ts
- packages/transformers/src/transformers/render-whitespace.ts
- packages/transformers/src/transformers/transformer-meta-highlight-word.ts
- packages/transformers/src/transformers/transformer-meta-highlight.ts
- packages/twoslash/src/core.ts
Due to the high frequency this function is used, it's better to expose it directly in the context to make the usage similar and avoid accidentally introducing unnecessary deps
> feat: add `addClassToHast` to transformer context

- docs/packages/twoslash.md
A few of the docs links point to a /@shikijs/ folder that isn't needed any longer
> docs: fix broken docs links to source

- packages/core/src/code-to-tokens-base.ts
- packages/core/src/types/options.ts
- packages/core/src/types/tokens.ts
- packages/monaco/src/index.ts
- packages/shiki/test/general.test.ts
Fix the textmate tokenizer freeze/crash the browser if a line is too long:
- Set the `timeLimit` parameter of `tokenizeLine2` to 500ms (align to vscode)
- Do not attempt to tokenize if a line is too long (enable by adding the `maxTokenizationLineLength` opion)
_
_Refs_
`timeLimit`:
https://github.com/microsoft/vscode/blob/3ce7ccff4116da34370cecfb329420f266499ec4/src/vs/workbench/services/textMate/browser/tokenizationSupport/textMateTokenizationSupport.ts#L54
Do not attempt:
https://github.com/microsoft/vscode/blob/6722b81416d8f1ee24209ca4a19792b6e6a55beb/src/vs/workbench/services/textMate/browser/tokenizationSupport/tokenizationSupportWithLineLimit.ts#L38
> feat: add length and time limit to tokenizer

- packages/core/src/utils.ts
- packages/shiki/test/ansi.test.ts
- packages/shiki/test/out/ansi-dark-plus.html
This PR fixes highlighting ansi with other themes than `monokai` (see #597).
#597
I've implemented an test for ansi with dark-plus. Which fails when removing the change to `packages/core/src/utils.ts`  Other themes didn't work either, but I didn't test them. Although they should be fine with this fix.
> fix: allow nullish color for colorReplacement, fix ansi highlighting with dark-plus, fix #597

- docs/guide/theme-colors.md
Added example for `colorReplacements` option in "Theme Colors Manipulation" section.
#601
> docs: added colorReplacements example

- docs/packages/transformers.md
Explicitly mention that the user is in charge of adding the css rules for classes added by transformers in the relevant section of the docs.
> docs: mention that the user is responsible for adding transformer classes css

- docs/guide/install.md
Had seen this when looking through the docs and shiki here didn't seem correct.
> docs: fix typo in install.md

- docs/.vitepress/components/ShikiMiniPlayground.vue
Currently, the demo on the home page of the docs is not displaying properly on Firefox, because the `textarea` that should allows visitors to edit the displayed code has the wrong dimensions :
This PR fixes this problem by setting explicitly the width and the height of the textarea to be 100% of its parent, which is the expected size.
I have checked in Chrome and Safari if this change had any unexpected consequences there, but as far as I can tell it looks exactly the same before and after it.
Fixes #613
> docs: fix the size of the home demo text area on firefox

- docs/guide/transformers.md
- docs/packages/transformers.md
- packages/transformers/README.md
👋, I've been working a lot with transformers recently as part of my day job.
I've made some edits to `@shikijs/transformers` the documentation which would have helped me understand them better without reading the source code.
I've been pretty aggressive with my rewrite -no problem fine if you decide to only take some of the parts / ideas (or none of it at all!) 👍 
Some of the ideas in this rewrite:
- Simplified the examples so they require less knowledge of javascript
- Example -> Render -> Explaination
- I tried to make each transformer be self contained (mentioning the CSS rules not included many times)
- I added `:3` range explanations 
- I explain what 'meta' is
- Highlight word docs mention it being occurences, but it's actually a range
Ideas to make this page even better (but I …
> docs: improve docs for transformers

- docs/packages/markdown-it.md
- docs/packages/rehype.md
- packages/core/rollup.config.mjs
- packages/core/src/types/index.ts
- packages/core/src/wasm-inlined.ts
- packages/shiki/src/bundle-full.ts
- packages/shiki/src/bundle-web.ts
- packages/shiki/src/wasm-dynamic.ts
- packages/shiki/test/core.test.ts
- packages/shiki/test/wasm1.test.ts
- packages/shiki/test/wasm2.test.ts
- packages/shiki/test/wasm3.test.ts
- packages/shiki/test/wasm4.test.ts
- tsconfig.json
Related: https://github.com/pi0/nuxt-shiki/issues/18
Performance improvements for reduce the request waterflow on requesting wasm binary.
Before this PR, `@shikijs/core/wasm-inlined` had an internal async chunk for lazy loading, but that take away the ability for users to have fine-grain control of when the chunk been loaded.
This PR makes the importing `shiki/wasm` and `@shikijs/core/wasm-inlined` directly import the binary within that chunk. So you can choice when and how to load the module.
More user-facing `import { getWasmInlined } from 'shiki'` renames unchanged
> perf: bundle wasm binary in chunk for `shiki/wasm` and `@shikijs/core/wasm-inlined`

- docs/.vitepress/config.ts
Because the *.vercel.app domain was blocked by China Mainland firewall policy, I changed the link to another domain, thus enhanced the reading experience for Simplified Chinese users.
Thank you.
> docs: change Chinese translation site link to make China Mainland accessible

- packages/vitepress-twoslash/src/index.ts
Passing `CreateTwoslashOptions` values to `options.twoslashOptions` did not have effect.
> fix(vitepress-twoslash): pass `options.twoslashOptions` to `createTwoslasher`

- packages/transformers/test/fixtures/focus/empty-line-comment.js
- packages/transformers/test/fixtures/focus/empty-line-comment.js.output.html
- packages/transformers/test/fixtures/highlight/empty-line-comment.js
- packages/transformers/test/fixtures/highlight/empty-line-comment.js.output.html
Shiki's focus and highlight transformers remove the `<span>` entirely if the comment line is otherwise empty.
This PR adds a fixture which tests this behavior.
This behavior is discussed in https://github.com/shikijs/shiki/issues/589
> test: transformer empty line fixtures

- packages/monaco/src/index.ts
current implement the `tokenize` method computes `colorMap` and `colorToScopeMap` every time it's called.
the patch moved the `colorMap` out of the `tokenize` method, only re-computes when `setTheme` is called.
no testing, but the code works in my wip editor:
https://github.com/shikijs/shiki/assets/2883484/28c99b23-ffff-4ed1-b27d-c41d41e56db8
> perf(shiki-monaco): improve tokenizer performance

- packages/core/src/internal.ts
- packages/core/src/registry.ts
This PR caches `getLoadedThemes()` and `getLoadedLanguages()` so they're only re-computed when needed.
`getLoadedThemes()` and `getLoadedLanguages()` are often hot APIs as they're used to check if themes or languages are loaded for lazy-loading additional themes and languages. This means that for every highlight, these functions could be called, and `Object.keys()` + fresh arrays are always constructed, which is taxing.
n/a
Examples of hot APIs:
- https://github.com/expressive-code/expressive-code/blob/b6e7167ac4014ab12d60a87c843379a3df87b5cc/packages/%40expressive-code/plugin-shiki/src/index.ts#L71
- https://github.com/expressive-code/expressive-code/blob/b6e7167ac4014ab12d60a87c843379a3df87b5cc/packages/%40expressive-code/plugin-shiki/src/index.ts#L85
- …
> refactor: cache getLoadedThemes and getLoadedLanguages

- packages/core/src/registry.ts
- packages/core/src/textmate.ts
This PR caches `createFromRawTheme` within `setTheme` to improve dual-theme support perf.
For dual-theme support, `registry.setTheme` is used to switch to a theme before processing a code. When this switch occurs, `Theme.createFromRawTheme` (from `vscode-textmate`) is used to transform the theme to its format and this function can be expensive when called many times.
Theme switches happen often here (following the stack down):
https://github.com/shikijs/shiki/blob/8653f88639ca50b77d03d73ea8e3ceb59cdd94a5/packages/core/src/code-to-tokens-themes.ts#L21-L26
https://github.com/shikijs/shiki/blob/8653f88639ca50b77d03d73ea8e3ceb59cdd94a5/packages/core/src/code-to-tokens-base.ts#L27
https://github.com/shikijs/shiki/blob/8653f88639ca50b77d03d73ea8e3ceb59cdd94a5/packages/core/src/internal.ts#L80-L8 …
> refactor: cache setTheme createFromRawTheme

- packages/transformers/src/transformers/notation-map.ts
- packages/transformers/test/fixtures/highlight/query.sql
- packages/transformers/test/fixtures/highlight/query.sql.output.html
…shikijs/shiki#654)
It was not possible to highlight a line in SQL using `-- [!code highlight]`.
I have added SQL comment notation (`--`) to the comment notation transformer.
https://github.com/shikijs/shiki/issues/654
> fix(transformers): allow SQL comment syntax in notation transformer, fix #654

- packages/core/src/oniguruma/index.ts
- packages/shiki/test/cf.ts
- packages/shiki/test/wasm5.test.ts
- packages/shiki/test/wasm6.test.ts
- Closes https://github.com/shikijs/shiki/issues/604
It looks like the exact usage of `loadWasm(import('shiki/onig.wasm'))`  shown in the documentation doesn't work currently https://shiki.style/guide/install#cloudflare-workers.
There is actually a different way to load wasm directly `WebAssembly.instantiate` as demonstrated in `packages/shiki/test/cf.ts` and it works. However, this usage seems a little more convoluted, so I'm suggesting to improve `loadWasm` utility to support `loadWasm(import('shiki/onig.wasm')` usage like in the documentation. 
https://github.com/shikijs/shiki/blob/044181dfd536f693dc0b7309db60837834182f89/packages/shiki/test/cf.ts#L11
I tested locally with `pnpm -C packages/shiki test:cf`, but It looks like this is not checked on CI.
Please let me know if it's desired …
> fix(core): simplify cloudflare wasm loading

- docs/guide/theme-colors.md
- packages/core/src/code-to-tokens-ansi.ts
- packages/core/src/code-to-tokens-base.ts
- packages/core/src/code-to-tokens.ts
- packages/core/src/types/tokens.ts
- packages/core/src/utils.ts
- packages/shiki/test/color-replacement.test.ts
Add scoped color replacements to limit color replacements to a specific theme. This is useful when multiple themes are provided.
Resolve #679
> feat: scoped color replacements

- packages/core/src/code-to-tokens-base.ts
This improves the performance for using `codeToTokens` with `includeExplanation` option enabled.
I'm working with a file that is 3k lines long, and getting the tokens with explanations was taking way too much time, around 7 to 9 seconds.
Turns out that the `explainThemeScope` function was redoing a decent amount of work for each token, for each scope, and for each setting, without depending on any of those. So it would be calculated once and reused.
Now I get tokens for that file in ~1.5s
Probably could be improved more, but I didn't want to change any logic.
> perf: improve performance for the `includeExplanation` option

- packages/rehype/src/core.ts
- packages/rehype/src/index.ts
The augmented hast `Data` interface conflicts with `ElementData` from `mdast-util-to-hast`. The augmentation is redundant, so it’s removed entirely.
The augmented hast `Properties` interface was redundant and invalid. Instead, the value is now converted to string in the place it is used.
https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/69775
You should only augment interfaces if you define something, not if you consume it.
> fix(rehype): fix type issues

- packages/core/src/code-to-tokens-base.ts
- packages/core/src/grammar-state.ts
- packages/core/src/highlighter.ts
- packages/core/src/registry.ts
- packages/core/src/types/highlighter.ts
- packages/core/src/types/options.ts
- packages/core/src/types/textmate.ts
- packages/core/src/types/tokens.ts
- packages/shiki/test/grammar-state.test.ts
Sometimes, we might want to highlight a partial of the code snippet, which might not necessarily be a full language statement. 
For example, if we want to highlight a TypeScript type annotation `Pick<MyObject, string>[]` we might do:
```ts
import { codeToHtml } from 'shiki'
const highlighted = await codeToHtml('Pick<MyObject, string>[]', { lang: 'ts', theme: 'github-dark' })
```
We will get the result like this:
This isn't accurate. This is because from the grammar, Shiki doesn't know it's a type annotation already.
Instead, we could append `let a: ` to our code to hint that:
```ts
import { codeToHtml } from 'shiki'
const highlighted = await codeToHtml('let a: Pick<MyObject, string>[]', { lang: 'ts', theme: 'github-dark' })
```
Which will now render:
While the highlighting is now correct, …
> feat: introduce `GrammarState`

- packages/core/src/code-to-tokens-themes.ts
The options's `includeExplanation` field in `codeToTokens` doesn't work!
> fix: codeToTokens's includeExplanation option

- docs/packages/rehype.md
- packages/rehype/src/core.ts
See: #724 and #723
Uable to prompt properties in the `CodeToHastOptionsCommon` type when I use `RehypeShikiOptions` options.
As mentioned in PR #724, it conforms to the `CodeToHastOptions` type, we should add it.
> fix(rehype): add the misssing `CodeToHastOptionsCommon` to `RehypeShikiCoreOptions` for `rehype` plugin

- packages/core/src/transformer-decorations.ts
- packages/core/src/types/decorations.ts
- packages/core/src/utils.ts
- packages/shiki/test/decorations.test.ts
- packages/shiki/test/out/decorations/basic.html
Fixes edge cases in the Decorations API.
Fix #719 (when `offset === code.length`)
Fix #727 (when `end.line < start.line` but `end.offset > start.offset`)
It's recoverable when `end.line < start.line` if the offsets are okay. But because of the test explicitly checking that the chars don't overflow the line, I followed suit and threw instead of manipulating the line/character.
> fix(core): fix decoration offset edge cases

- packages/core/src/code-to-tokens-base.ts
- packages/core/src/types/tokens.ts
- packages/shiki/test/__snapshots__/tokens.test.ts.snap
- packages/shiki/test/tokens.test.ts
> feat(core): lighter token explanation with `scopeName`

- packages/transformers/src/transformers/notation-map.ts
Add more comment style
|language|comment prefix|
|---|---|
|`vim`|`"`|
|`vb`|`'`|
|`lisp`|`;;` or `;`|
|`latex`|`%`|
|`mermaid`|`%%`|
none
https://regex101.com/r/qm9CzU/1
> fix(transformers): support more comment style for notation transformer

- packages/twoslash/src/core.ts
- packages/twoslash/src/includes.ts
- packages/twoslash/src/types.ts
- packages/twoslash/test/includes.test.ts
- packages/twoslash/test/out/includes/main.html
- packages/twoslash/test/out/includes/replaced_directives.html
The `@include` feature that was demonstrated on the documentation for shiki-twoslash-v0 doesn't work with the newer version.
This is because remark-shiki-twoslash (which was used on the old documentation website) would handle the caching and replacement of code with this feature prior to passing the transformed result to twoslash. [See here](https://github.com/shikijs/twoslash/blob/42015c138b41f1618f0df74d72e8f3ecc8f844ef/packages/remark-shiki-twoslash/src/index.ts#L73).
- Port the utilities for `includes` from [remark-shiki-twoslash](https://github.com/shikijs/twoslash/blob/42015c138b41f1618f0df74d72e8f3ecc8f844ef/packages/remark-shiki-twoslash/src/includes.ts) to `@shikijs/twoslash`
- Add a string parser utility to identify `include [name]` in raw meta tags.
- Initialize a new map …
> feat(twoslash): support `@includes`

- bench/engines.bench.ts
- packages/core/src/constructors/highlighter.ts
- packages/core/src/constructors/internal-sync.ts
- packages/core/src/constructors/internal.ts
- packages/core/src/index.ts
- packages/core/src/textmate/getters-resolve.ts
- packages/core/src/textmate/registry.ts
- packages/core/src/types/engines.ts
- packages/core/src/types/highlighter.ts
- packages/core/src/types/options.ts
- packages/core/src/utils.ts
- packages/markdown-it/test/index.test.ts
- packages/shiki/test/core-sync.test.ts
- packages/shiki/test/core.test.ts
This PR introduces two exports `createShikiInternalSync` and `createHighlighterCoreSync` that allow completely synchronous usage of Shiki. (made possible by forking `vscode-textmate` as https://github.com/shikijs/vscode-textmate)
For example:
```ts
import { createHighlighterCoreSync, createJavaScriptRegexEngine } from 'shiki/core'
import js from 'shiki/core/langs/javascript.mjs'
import nord from 'shiki/core/themes/nord.mjs'
const shiki = createHighlighterCoreSync({
themes: [nord],
langs: [js],
engine: createJavaScriptRegexEngine()
})
const html = shiki.highlight('console.log(1)', { lang: 'js', theme: 'nord' }) 
```
These APIs require explicit `engine` field to be provided, and all `langs` and `themes` should be provided as already-resolved objects. Combining with …
> feat: synchronous Shiki usage

- packages/shiki/scripts/prepare/langs.ts
- packages/shiki/scripts/prepare/themes.ts
This PR changes the bundled grammars and themes to use `JSON.parse("{...}")` instead of plain JS object `{...}`. This would hugely improve the re-bundling speed and memory usage as the compiler don't need to create many unused AST for the data inside.
This should have no effects to the end user usage
> feat(perf): wrap json data with `JSON.parse` to speed up rebundling

- packages/core/src/highlight/code-to-hast.ts
- packages/types/src/transformers.ts
Sometimes, we need to process some information in `transformer.tokens` and then record some additional information in the `token`, which will later be processed into the tokenNode in the `transformer.span` for rendering in HTML.
For example, I need to add a background color to tokens within a specific range. I need to split the tokens in `transformer.tokens` and add special markers, but I can't easily render these markers in `transformer.span`.
Now I am using the modified `tokenNode.htmlStyle` field to workaround, but I feel that exposing it in `transformer.span` would be better.
No linked issue
If you feel that this PR does not align with Shiki's design philosophy, you can close it, thanks
> feat(core): pass raw token to `transformer.span` api

- packages/markdown-it/test/index.test.ts
- packages/shiki/scripts/prepare/langs.ts
- packages/shiki/src/assets/langs-bundle-web.ts
- packages/shiki/test/bundle.test.ts
- packages/shiki/test/general.test.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
This PR introduces an optimization to load and bundle embedded languages lazily for some languages.
For example, in Vue SFC, you can have `<script lang="tsx">`, `<template lang="pug">`, `<style lang="scss">` to embed different languages in Vue files. This means to support properly support them, when loading Vue's grammar, it will also load `tsx`, `jsx`, `pug`, `coffee`, `scss`, `sass`, `less`... as it's dependencies - even you might not need most of the languages.
In this PR, we make those embedded languages as lazy dependencies, meaning they are not initiated along with `vue`. Instead, you need to load the corresponding languages alongside them to get those embedded blocks properly highlighted. We consider this as a performance improvement on both runtime and bundle size, as this would …
> feat(perf): lazy embed languages bundle for SFCs and Docs

- packages/core/src/constructors/bundle-factory.ts
- packages/core/src/constructors/highlighter.ts
- packages/core/src/highlight/code-to-hast.ts
- packages/core/src/highlight/code-to-tokens-base.ts
- packages/core/src/highlight/code-to-tokens-themes.ts
- packages/core/src/highlight/code-to-tokens.ts
- packages/core/src/textmate/grammar-state.ts
- packages/engine-javascript/test/__records__/html-basic.json
- packages/engine-javascript/test/__records__/json-basic.json
- packages/engine-javascript/test/__records__/jsonc.json
- packages/engine-javascript/test/__records__/sql.json
- packages/engine-javascript/test/__records__/toml.json
- packages/engine-javascript/test/__records__/ts-basic.json
- packages/engine-javascript/test/__records__/vue.json
- packages/shiki/test/grammar-state.test.ts
- packages/types/src/highlighter.ts
- packages/types/src/tokens.ts
In https://github.com/shikijs/shiki/pull/712, we introduced GrammarState to resume the highlighting from the middle way. It solves the problem of customizing grammar context, but wasn't very useful for passable highlighting (for example, in a text editor, instead of highlighting the full context again over again, we can reuse the result from the previously highlighted lines) - because users need to run the parsing twice to get the `GrammarState` object. The existing API wasn't designed to be able to return extra property, making it hard to return the `GrammarState` in one-go, without breaking changes.
This PR overcharges the `shiki.getLastGrammarState()` function to be able to accept the return Hast `Root` or `ThemedToken[][]` to retrieve the `GrammarState` stored in a internal WeakMap. …
> feat: store grammar state in weakmap

- packages/rehype/src/core.ts
- packages/rehype/test/fixtures/a.core.out.html
- packages/rehype/test/fixtures/a.md
- packages/rehype/test/fixtures/a.out.html
Currently, special languages like `plaintext` and `txt` are treated as normal languages.
When `lazy` is not enabled, codeblocks with special languages will be ignored because `highlighter.getLoadedLanguages()` will never contain these languages.
This PR adds a check for `isSpecialLang` to allow styling codeblocks with special languages.
#805
> fix(rehype): support special languages

- docs/packages/twoslash.md
Update the links to integrations from  from https://shiki.style/packages/twoslash#integrations:
- Updated the link to Slidev integration
- Updated the link to Nuxt integration
None
When I was at https://shiki.style/packages/twoslash#integrations
1. The Slidev link pointed to the 404 page. The TwoSlash Integration has been moved to https://sli.dev/features/twoslash#twoslash-integration therefore updating it in docs.
2. The Nuxt link pointed to non-existing hash (i.e. `#twoslash`) while the correct one was `#twoslash-integration`
> docs: update Slidev & Nuxt links

- packages/core/src/constructors/bundle-factory.ts
While playing with JavaScript Regex engine and `getSingletonHighlighter`, I noticed that the WASM engine was loaded regardless of my `engine` option, and it is indeed using the JavaScript engine.
After looking into the codebase, I found:
```ts
const core = await createHighlighterCore({
engine: engine(),
```
In the code of `createdBundledHighlighter` (highlighter factory), this causes `engine` to be called and hence the WASM engine is loaded with lazy import, even if it is unused.
N/A
> fix(core): `createdBundledHighlighter` cause wasm engine to be loaded

- packages/shiki/scripts/prepare/langs.ts
Fixes a typo in the language preparation script where `STANDALONG_LANGS_EMBEDDED` was misspelled. The constant is used to identify languages that should be kept standalone in the language bundling process.
Changed `STANDALONG` -> `STANDALONE` in the variable name to improve code readability and maintain consistent naming conventions.
N/A
This is a simple typo fix in the prepare script variable name. The functionality remains unchanged as this only affects the variable naming.
> fix: typo STANDALONG -> STANDALONE in prepare script

- docs/guide/transformers.md
Currently the docs imply that Shiki provides a parsed meta object. This change removes that implication. This change also provides an example of dashcased meta attribute keys and quoted meta attribute values.
- #792
> docs(transformers): clarify that shiki does not parse meta

- docs/guide/regex-engines.md
- docs/references/engine-js-compat.md
- packages/engine-javascript/src/index.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
- scripts/report-engine-js-compat.ts
- Shiki 1.23.0
- 178 supported, 18 mismatched, and 18 unsupported.
- *Forgiving:* **183** supported, 31 mismatched, 0 unsupported.
- With this PR 🎉
- 192 supported, 10 mismatched, 13 unsupported.
- *Forgiving:* **197** supported, 18 mismatched, 0 unsupported.
(The *forgiving* supported count is more accurate, since it's copying the Oniguruma engine's behavior of silently failing for regexes with invalid Oniguruma syntax.)
Changes that enabled this improvement are described in the `Oniguruma-To-ES` [release notes](https://github.com/slevithan/oniguruma-to-es/releases) for versions 0.3.0 and 0.4.0.
Is this still experimental? Probably. But I thought I'd raise the question since, although it can continue to improve in various ways (supporting a few more grammars, improving performance, …
> feat: bump Oniguruma-To-ES dep to support more grammars and simplify

- docs/guide/regex-engines.md
- docs/references/engine-js-compat.md
- packages/engine-javascript/test/compare.test.ts
- packages/engine-javascript/test/general.test.ts
- packages/shiki/test/core-sync.test.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
- scripts/report-engine-js-compat.ts
Bumps `oniguruma-to-es` to patch [v0.6.1](https://github.com/slevithan/oniguruma-to-es/releases) to improve JS engine support when using `target: 'ES2018'`. This includes cases when `target: 'auto'` is used in pre-ES2024 environments like Node.js 18. I've also updated the JS engine tests to run in such environments.
> feat: improve js engine support (and run tests) in pre-ES2024 envs

- docs/references/engine-js-compat.md
- pnpm-lock.yaml
- pnpm-workspace.yaml
Latest [`oniguruma-to-es`](https://github.com/slevithan/oniguruma-to-es) adds support for more grammars (193 ➜ 197).
(Since there have been a few recent related PRs, note that I don't expect additional updates in the near future unless bug fixes are needed.)
> feat: bump js engine dependencies to support more grammars

- docs/packages/next.md
Remove `@ts-expect-error -- untyped` for the `jsx` and `jsxs` imports from `react/jsx-runtime`
--
I am thinking that this has been released with the React 19 types?
> docs: remove @ts-expect-error for untyped jsx, jsxs

- docs/packages/next.md
Pass in:
1. code and language via props for `<CodeBlock>` component
2. language via 2nd `highlight()` function parameter
--
--
> docs: pass CodeBlock/highlight code + lang in as props, parameter

- docs/packages/next.md
Add TypeScript type assertion to the `React.JSX.Element` type, because `hast-util-to-jsx-runtime` will not update types for React 19:
- https://github.com/syntax-tree/hast-util-to-jsx-runtime/issues/10#issuecomment-2523396087
The `hast-util-to-jsx-runtime` project recommends adding back the JSX global namespace:
- https://github.com/syntax-tree/hast-util-to-jsx-runtime/issues/10#issuecomment-2523893859
But this seems like an unusual way, considering that the ecosystem is moving away from that.
So I suggest the type assertion to work around this.
@antfu if you would prefer a different type eg. `ReactElement` or some other method like adding back the global `JSX` namespace, I can do that instead.
--
--
> docs: add type assertion to React.JSX.Element type

- docs/packages/next.md
Adds a missing import in the Next JS `codeblock.ts` docs example when using `shiki` client-side.
> Add missing JSX import

- docs/references/engine-js-compat.md
- packages/engine-javascript/src/index.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
Bumps `oniguruma-to-es` to [0.9.0](https://github.com/slevithan/oniguruma-to-es/releases), moving C++ and Apex from *Mismatched* to *Supported* in the JS engine report.
These improvements to `oniguruma-to-es` required complex changes in the base library and a couple dependencies. Heads up that this version also externalized dependencies in `oniguruma-to-es`'s ESM bundle.
There are only two languages left under *Mismatched*: Kusto and NGINX.
- Kusto is blocked by an Oniguruma bug ([see details](https://github.com/rosshamish/kuskus/issues/209)). The JS engine is actually the one producing the correct results.
- Running the NGINX sample through `compare.test.ts` produces identical output for the JS and WASM engines. I'm not sure how to investigate further.
> feat(engine-js): update deps, support new languages

- docs/guide/regex-engines.md
Various small improvements/updates/tweaks for <https://shiki.style/guide/regex-engines>. Feel free to undo any of the changes.
An underlying motivation for some of these changes was to avoid discouraging use of the JS engine (while still providing all relevant details and warnings) now that it is stable and more robust.
This doesn't add mention of the JS engine for precompiled grammars (added in Shiki v1.26) since I think it's best for @antfu to do the first pass for that.
> docs: more details about regexp engines

- docs/references/engine-js-compat.md
- packages/engine-javascript/src/engine-compile.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
- Bumps `oniguruma-to-es` from `0.10.0` to `^1.0.0`.
- Adds `rules.recursionLimit` and sets it to `5`. This reproduces the default behavior of v0.3.0 to v0.10.0.
- v1.0.0 changed the default recursion depth limit to `20` to match Oniguruma.
- v1.0.0 drops support for the CodeQL grammar because it contains an invalid Oniguruma regex that `oniguruma-to-es` is now able to detect (use of lookahead within lookbehind).
- The grammar works the same in the Oniguruma and JS RegExp engines if `forgiving` is enabled.
> chore: update oniguruma-to-es and use new api

- docs/guide/regex-engines.md
- docs/references/engine-js-compat.md
- packages/engine-javascript/src/engine-compile.ts
- packages/langs-precompiled/scripts/__snapshots__/precompile.test.ts.snap
- pnpm-lock.yaml
- pnpm-workspace.yaml
- scripts/report-engine-js-compat.ts
Bumps `oniguruma-to-es` to [v2.0.0](https://github.com/slevithan/oniguruma-to-es/releases), which adds comprehensive support for `\G`.
- Moves NGINX from Mismatched to Supported.
- There are no longer ***any*** mismatched languages. 🎉✨ Languages are now either supported or not.
- Removed option `rules.ignoreUnsupportedGAnchors`. It no longer exists, because it's no longer useful (all `\G`s are supported).
- Despite the fact that the only remaining sample affected by the incomplete `\G` support was NGINX, it was a big concern of mine that, until now, ~30% of grammars still had at least one `\G` that was ignored. In most cases that probably meant there was at least some edge case where the highlighting would be mismatched.
- **Removing this option in this new release is a huge milestone, …
> feat(engine-js): update deps, support more languages

- docs/guide/best-performance.md
- docs/guide/regex-engines.md
- docs/references/engine-js-compat.md
- packages/engine-javascript/src/engine-compile.ts
- packages/langs-precompiled/scripts/__snapshots__/precompile.test.ts.snap
- pnpm-lock.yaml
- pnpm-workspace.yaml
- Updates `oniguruma-to-es` to v2.2.0.
- Reduces Razor errors from 5 to 3 via new support for group names that are invalid JS identifiers but valid in Oniguruma.
- Applies new option `rules.singleline` (Oniguruma option `ONIG_OPTION_SINGLELINE`).
- Changes transpiled output for `^` and `$`.
- Improves performance of some grammars without any change in meaning since TM grammars are applied line by line.
- Tweaks new perf-related documentation.
> feat(engine-js): improve performance for some languages

- packages/rehype/src/core.ts
This PR improves the performance of `lazy` by:
- Instead of always add tasks to a queue, it highlights nodes in sync if the language is loaded.
- Only return promise (async) if unloaded language is found.
- Cleaned some code, and removed one unnecessary function.
N/A
> fix(rehype): improve `lazy` performance

- docs/.vitepress/config.ts
- docs/.vitepress/theme/index.ts
- docs/.vitepress/vite.config.ts
- docs/package.json
- docs/packages/cli.md
- docs/packages/colorized-brackets.md
- docs/packages/markdown-it.md
- docs/packages/monaco.md
- docs/packages/rehype.md
- docs/packages/transformers.md
- docs/packages/twoslash.md
- docs/packages/vitepress.md
- pnpm-lock.yaml
- pnpm-workspace.yaml
This PR includes:
1. Add [vitepress-plugin-group-icons](https://github.com/yuyinws/vitepress-plugin-group-icons) to enhance the document's readability.
2. Improve the `install` paragraph for the `Integrations` section.
> docs: add `vitepress-plugin-group-icons`

- packages/rehype/src/core.ts
- packages/rehype/src/types.ts
- packages/rehype/test/core.test.ts
- packages/rehype/test/fixtures/d.md
- packages/rehype/test/fixtures/d.out.html
Support `fallbackLanguage` when `lazy` is set to true, you can consider this as a successor of #821.
Since `highlighter.loadLanguage` throws error on languages that's not included in the bundle, we can use it to detect whether fallback is needed.
N/A
Unit test added
> feat(rehype): Support `fallbackLanguage` on lazy mode

- docs/guide/transformers.md
Just adding a missing backtick to the name of an NPM package in the docs
None
None
> docs: fix missing backtick

- docs/references/engine-js-compat.md
- packages/engine-javascript/src/engine-compile.ts
- packages/langs-precompiled/scripts/__snapshots__/precompile.test.ts.snap
- packages/langs-precompiled/scripts/langs.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
- Bump `oniguruma-to-es` from v2.3.0 to v3.1.0, and migrate for breaking changes.
- Lazy compile patterns with a transpiled length ≥ 3000.
- For precompiled grammars, this should improve initialization time if the grammar includes extremely long patterns, and improve overall time if the lazy-compiled regexes aren't always used.
> feat(engine-js): lazy compile extremely long patterns

- docs/references/engine-js-compat.md
- The grammar traversal fix in Shiki 2.3.1 updated a lot of regex counts in the compat report.
- The `tm-grammar` bump in Shiki 2.3.1 included an upstream PR I landed for C#, which added C# and Razor to the supported list.
> chore: update js engine compat report

- docs/packages/nuxt.md
Due to the release of nuxt content v3, the link to the config has changed
> docs: update link to @nuxt/content options

- packages/monaco/src/index.ts
- packages/monaco/src/tokenizer.ts
- packages/monaco/src/types.ts
- packages/monaco/src/utils.ts
- removed `any` types
- added indentations for better readability
- helper functions moved to `./utils.ts`
- types in `./types.ts`
> refactor(packages/monaco): decomposed into logical parts

- packages/monaco/src/index.ts
> fix(monaco): handle missing settings in textmate theme func

- docs/references/engine-js-compat.md
- pnpm-lock.yaml
- pnpm-workspace.yaml
Bumps `oniguruma-to-es` to v3.1.1, which includes a workaround for a WebKit regex parser bug that is affecting at least the YAML grammar. Fixes #927.
> feat(engine-js): bump deps to work around Safari bug with some grammars

- docs/guide/regex-engines.md
Per discussion separately, adding a warning discouraging the use of precompiled languages for now until #918 is resolved.
> chore: warn in docs that precompiled langs aren't yet supported

- docs/guide/compat.md
- docs/guide/regex-engines.md
Warnings aren't being displayed correctly in the docs. This fixes it.
> docs: fix markup for warnings

- docs/packages/markdown-it.md
- docs/packages/rehype.md
In 3.0 version, `loadWasm` field in `createHighlighterCore` is replaced with `engine` field while the examples are still incorrect.
> docs: fix markdown-it and rehype examples

- docs/.vitepress/config.ts
Improve docs local development setup experience. Make it literally work. ⚡
Hi maintainers! Today I tried to set up a local development environment for self-testing and ready for contributions. Gladly, I found the `CONTRIBUTING.md` and followed the steps. 
However, it doesn't work out well... 😢 The issue arises from some essential configurations being missed, leading to problems for users.
> fix: failed to run shiki docs server locally

- docs/guide/install.md
Update `shiki` version to v3.0.0 in [CDN Usage](https://shiki.matsu.io/guide/install#cdn-usage)
Yesterday, my friend wanted to download `shiki` through CDN but the documentation didn't provide the latest version to her. I think it would mislead others as well, especially for the newbies who can't find help but fully trust the documentation.
|Before|After|
|:---:|:---:|
|<img width="800" alt="image" src="https://github.com/user-attachments/assets/51ef9c23-00e8-4e51-a511-abf7b1019e29" />|<img width="800" alt="image" src="https://github.com/user-attachments/assets/0474d959-47e5-41a8-92d3-4af988179cbb" />|
> docs: update CDN shiki version to v3.0.0 (current)

- docs/.vitepress/theme/transformers.css
- docs/languages.md
- packages/cli/src/code-to-ansi.ts
- packages/core/src/highlight/code-to-hast.ts
- packages/core/src/highlight/code-to-tokens-ansi.ts
- packages/core/src/utils/tokens.ts
This PR adds support for handling the `FontStyle.Strikethrough` in a few places where it was not present. The primary motivation was to support ANSI strikethrough which is supported by the underlying `ansi-sequence-parser` package but not by Shiki.
Fixes #975 by myself
I would appreciate any help in pointing out the new test cases which should be added to cover the changed code (and where to add them).
> feat: add handling for `FontStyle.Strikethrough`

- docs/guide/regex-engines.md
- docs/references/engine-js-compat.md
- pnpm-lock.yaml
- pnpm-workspace.yaml
- Updates to `regex-engines.md` for clarity.
- Bump `oniguruma-to-es`, and rerun the engine compatibility report (no changes).
> docs: clarify that the `forgiving` option is for unsupported languages

- packages/transformers/src/transformers/remove-notation-escape.ts
Support usage with `rehypeShiki`, which doesn't support `postprocess` and some other transformer hooks.
This is possible by using `line` hook instead.
fixes #1010
> feat(transformers): `transformerRemoveNotationEscape` support rehype plugin usage

- packages/core/src/highlight/code-to-hast.ts
- packages/core/test/hast.test.ts
This PR fixes an issue where adjacent tokens with identical styles weren't being merged correctly when multiple themes were applied.
Debug logs showed that even though prevStyle and currentStyle contained the same CSS properties, the === comparison was returning false because they were different object instances.
fix #1003
> fix: correct style comparison logic in mergeAdjacentStyledTokens

- docs/guide/dual-themes.md
- packages/core/src/highlight/code-to-tokens.ts
- packages/core/src/utils/_constants.ts
- packages/core/src/utils/tokens.ts
- packages/core/test/__snapshots__/tokens.test.ts.snap
- packages/core/test/tokens.test.ts
- packages/types/src/options.ts
This pull request introduces support for the `light-dark()` CSS function in the Shiki library, allowing for dynamic theme switching between light and dark modes using CSS variables. It includes updates to the core logic, documentation, and tests to implement and validate this feature.
API-wise, it adds `useLightDarkFunction` option to enable this feature.
- https://github.com/shikijs/shiki/issues/1027
This is my first PR to the Shiki project.  I'm new to the codebase, so please let me know if I've missed anything or if there are any project conventions I should follow more closely.
I'm happy to make any changes as needed.  Thank you for your review and guidance!
> feat: add support for CSS `light-dark()` function in dual themes

- docs/guide/dual-themes.md
simply fix an error in the doc. It is mentioned that the themes's key is `options` when in fact it is `themes`
> docs: Update dual-themes.md to fix key name

- packages/langs/scripts/langs.ts
- packages/shiki/test/astro.test.ts
Personally, I think that unlike Vue, Astro should not include 'tsx' in embeddedLangsLazy, as doing so causes the syntax highlighting issue with curly braces mentioned in issue #830.
fixes #830
> fix(shiki): astro partial syntax highlighting error

- packages/twoslash/src/renderer-rich.ts
I've been experimenting with using twoslash for a non-Typescript language.
I've gotten this to mostly work by providing a custom "twoslasher" to `createTransformerFactory` to inject type information:
```typescript
transformers: [
createTransformerFactory(
(code, filename, options) => {
nodes = /* code to insert hover with types / errors here */;
return {
code: code,
nodes,
};
},
rendererRich({
lang: 'julia',
processHoverInfo: text => text,
}),
)
}
```
This works well, except for the `codeToHast` call in the rich renderer, which overrides the language used to syntax highlight the type in any `'hover'` nodes, etc.
> fix(twoslash): pass-through unrecognized `options.lang` to `codeToHast`

- packages/vitepress-twoslash/src/client.ts
This PR makes it more convenient for users to modify existing themes.
> [!IMPORTANT]
> One thing to note: I've changed the `theme` option to `themes` to align with upstream naming. This is a **breaking change**, so if you prefer, I can move this adjustment to a separate PR. Just let me know!
Related: https://github.com/vueuse/vueuse/issues/4983
> feat(vitepress-twoslash): improve UX for option customization

- .github/workflows/ci.yml
- .github/workflows/release.yml
Enable trusted publisher, required steps:
1. Connect shiki repository to all npm packages at `https://www.npmjs.com/package/<package-name>/access`
2. Safely remove npm tokens and `CODECOV_TOKEN`
3. [optional] Disallow tokens and trusted publishing will still work
https://github.com/e18e/ecosystem-issues/issues/201
> ci: use oidc for npm publish & codecov
