CHANGELOG.md
packages/languages/data/grammars/java.json

(java): added 'strictfp' to storage modifiers

---

packages/themes/data/vscode/light_plus.json

Fixes https://github.com/octref/shiki/issues/40

Update light_plus.json to latest vscode version

---

packages/themes/data/vscode/dark_vs.json

fix: fix brace color in dark_plus

---

README.md

We are using shiki at blockstack for our docs: https://docs.blockstack.org, in combo with mdx, next.js, remark/rehype :)

update readme: add blockstack

---

packages/vuepress-plugin/index.js

Copied from
https://github.com/shikijs/shiki/blob/58cb92cd9427a97d5b4f89e3cec8e12290fcb793/packages/shiki/src/renderer.ts#L39-L49

Fix #63 for vuepress plugin

---

packages/themes/README.md

just adding a note since its a natural question to ask :)

add note on where to preview themes

---

packages/languages/README.md
packages/languages/data/elixir.tmLanguage.json
packages/languages/src/lang.ts
scripts/pullGrammarsFromGitHub.js

For info the "update:grammars" command deleted a lot of languages so I did the changes manually.
Nice project :)

Add Elixir grammar

---

packages/shiki/src/highlighter.ts

Mark Highligher.codeToHtml as non-nullable

---

packages/languages/README.md
packages/languages/data/asp-net-razor.tmLanguage.json
packages/languages/src/lang.ts
scripts/pullGrammarsFromGitHub.js

Add the grammar for ASP.NET Core Razor (`asp-net-razor`).

Add ASP.NET Core Razor grammar

---

.github/workflows/CI.yml
docs/languages.md
packages/shiki/languages/html-ruby-erb.tmLanguage.json
packages/shiki/src/languages.ts
scripts/updateLangSrc.js

I guess they won't fail because the script is set to throw, but at least it's definitely going through the process

Adds erb alias, and tests languages/themes downloading on CI 

---

packages/shiki/src/renderer.ts

fix: wrap empty lines with span

---

packages/shiki/src/loader.ts
packages/shiki/src/types.ts

I _assume_ this is the intention in https://github.com/shikijs/shiki/commit/0f1739944c6047ba09fca4a2000992ba149aff7f

Fix master

---

README.md

You suggested this be done in #140

add vpc-shiki to example projects

---

docs/themes.md
packages/shiki/src/themes.ts
packages/shiki/themes/dracula-soft.json
packages/shiki/themes/dracula.json
scripts/themeSources.ts

feat: dracula themes

---

packages/shiki/package.json

Fix webpack apps targeting browsers

---

docs/languages.md
packages/shiki/languages/dream-maker.tmLanguage.json
packages/shiki/samples/dm.sample
packages/shiki/src/languages.ts
scripts/grammarSources.ts

For the sample i just yanked the code from an actual game (https://github.com/tgstation/tgstation)

Adds DreamMaker language support

---

docs/themes.md
packages/shiki/src/themes.ts
packages/shiki/themes/vitesse-dark.json
packages/shiki/themes/vitesse-light.json
scripts/themeSources.ts

https://github.com/antfu/vscode-theme-vitesse

feat: add vitesse theme

---

.github/workflows/CI.yml
.github/workflows/deploy.yml
.github/workflows/update-grammars.yml
packages/renderer-svg/package.json
packages/shiki/package.json
packages/site/index.md

Pleb will deploy npm packages if they have a version which isn't on npm yet. So to make a release you just change the package version and push.

Handle master -> main, and add a CI deploy step via pleb

---

README.md

Adding [Torchlight](https://torchlight.dev) to the Readme, per our twitter convo.
Thanks!

Add Torchlight to "Seen" section

---

packages/shiki/package.json

Release includes several things, what I care about is 5732ed66da83d23ed711b2ad146a69a78f52ab00

Bump version to 0.9.8

---

packages/shiki/languages/csharp.tmLanguage.json
scripts/grammarSources.ts

fix: update to latest grammar from dotnet/csharp repo. fix #219

---

docs/languages.md
packages/shiki/languages/ballerina.tmLanguage.json
packages/shiki/samples/ballerina.sample
packages/shiki/src/languages.ts
scripts/grammarSources.ts

Add Ballerina language textmate grammar.
[Website](https://ballerina.io)
[Github](https://github.com/ballerina-platform/ballerina-lang)

Add Ballerina language support

---

README.md

I put it 2nd as it's a pretty solid showcase for shiki

Add Shiki Twoslash to the README.md

---

docs/languages.md

Adds some docs on using your own languages re: https://github.com/shikijs/twoslash/issues/119

docs: Update languages.md to show how to add your own language

---

packages/shiki/src/highlighter.ts
packages/shiki/src/registry.ts

- [n/a] Add a test if possible
- [n/a] This PR fixes #
- [n/a] I have read docs for [adding a theme](/docs/themes.md#adding-theme).
- [n/a] I have read docs for [adding a language](/docs/languages.md#adding-grammar).
- [n/a] I have searched around and this is the most up-to-date, actively maintained version of the language grammar.
- [n/a] I have added a sample file that includes a variety of language syntaxes and succinctly captures the idiosyncrasy of a language. See [docs](/docs/languages.md#adding-grammar) for requirement.

fix typo: grammer -> grammar

---

packages/shiki/src/highlighter.ts

fix: use the same type definition for theme

---

docs/themes.md
packages/shiki/src/themes.ts
packages/shiki/themes/alternight.json
scripts/themeSources.ts

Add my AlterNight VS Code theme (https://github.com/spaceinvadev/alternight-vscode-theme).

feat: add alternight theme

---

README.md

https://github.com/sachinraja/shiki-renderer-pdf

docs: add shiki-renderer-pdf to "Seen" in readme

---

docs/languages.md
packages/shiki/languages/bicep.tmLanguage.json
packages/shiki/samples/bicep.sample
packages/shiki/src/languages.ts
scripts/grammarSources.ts

feat: add bicep support

---

docs/languages.md
packages/shiki/languages/berry.tmLanguage.json
packages/shiki/samples/berry.sample
packages/shiki/src/languages.ts
scripts/grammarSources.ts

- [ x] I have read docs for [adding a language](/docs/languages.md#adding-grammar).
- [ x] I have searched around and this is the most up-to-date, actively maintained version of the language grammar.
- [ x] I have added a sample file that includes a variety of language syntaxes and succinctly captures the idiosyncrasy of a language. See [docs](/docs/languages.md#adding-grammar) for requirement.

Add Berry Grammar

---

README.md

Adding [Code Hike](https://codehike.org/) to the readme.

docs: add Code Hike to "Seen"

---

docs/languages.md
packages/shiki/languages/rel.tmLanguage.json
packages/shiki/samples/rel.sample
packages/shiki/src/languages.ts
scripts/grammarSources.ts

feat: add rel lang

---

docs/languages.md
packages/shiki/languages/glsl.tmLanguage.json
packages/shiki/samples/glsl.sample
packages/shiki/src/languages.ts
scripts/grammarSources.ts

Add support for OpenGL Shading Language (GLSL)

feat: add glsl lang

---

packages/shiki/package.json
pnpm-lock.yaml

vscode-textmate@6.0.0

---

docs/languages.md
packages/shiki/src/languages.ts

fix: add 'yml' as an alias for yaml

---

packages/shiki/src/types.ts

Update the JSDoc comment to reflect the actual runtime behavior.

doc: update `HighlighterOptions.langs` JSDoc

---

docs/languages.md
packages/shiki/languages/blade.tmLanguage.json
packages/shiki/samples/blade.sample
packages/shiki/src/languages.ts
scripts/grammarSources.ts

feat: Add blade lang

---

docs/languages.md
packages/shiki/languages/proto.tmLanguage.json
packages/shiki/samples/proto.sample
packages/shiki/src/languages.ts
scripts/grammarSources.ts

**(This is the most downloaded language support on VS Code.)**

feat: add proto grammar

---

docs/languages.md
packages/shiki/languages/imba.tmLanguage.json
packages/shiki/samples/imba.sample
packages/shiki/src/languages.ts
scripts/grammarSources.ts

add imba as a shiki syntax

---

README.md

fix: minor doc updates

---

packages/renderer-svg/src/measureMonospaceTypeface.ts
packages/shiki/src/loader.ts
packages/shiki/tsconfig.json
pnpm-lock.yaml
tsconfig.json

fix: Type errors in Node projects without DOM lib

---

docs/languages.md
packages/shiki/languages/http.tmLanguage.json
packages/shiki/samples/http.sample
packages/shiki/src/languages.ts
scripts/grammarSources.ts

feat(lang): add HTTP language

---

README.md

Documentation update for specifying MIME types on reverse proxies
Fixes #400

 doc: add pointer to reverse proxe MIME config

---

docs/languages.md
packages/shiki/languages/yaml.tmLanguage.json
packages/shiki/src/languages.ts
scripts/grammarSources.ts

Added the `yml` alias for the `yaml` language

feat: add yml alias for yaml language

---

README.md

chore: remove useless parentheses

---

docs/languages.md
packages/shiki/src/languages.ts

fix(languages): add aliase dokerfile for docker

---

.github/workflows/CI.yml
package.json
pnpm-lock.yaml

@muenzpraeger `dlx` causes a version mismatch. FYI: https://github.com/microsoft/playwright/issues/19562

fix: remove dlx to avoid playwright version mismatch

---

docs/languages.md
packages/shiki/languages/nextflow.tmLanguage.json
packages/shiki/samples/nextflow.sample
packages/shiki/src/languages.ts
scripts/grammarSources.ts

feat: add nextflow grammar

---

packages/shiki/src/loader.ts

Add bun support

---

docs/languages.md
packages/shiki/src/languages.ts
scripts/grammarSources.ts

This pr adds `wl` alias for `wolfram`.

feat: add `wl` alias for `wolfram`

---

docs/guide/dual-themes.md

The current link references a completely unrelated issue, likely accidentally replaced when migrating to this repo.

docs: correct CSS variables issue link

---

docs/packages/rehype.md

Remove meaningless parts from sample code snippets to avoid confusion

chore: update rehype.md example

---

docs/guide/migrate.md

These should be `-shikiji`, not `-shiki`.

docs: fix migration guide

---

docs/packages/rehype.md

docs: typo

---

docs/guide/install.md
docs/guide/load-theme.md

docs: fix typo

---

docs/index.md

This fixes a few small things about the grammar on the home page of the docs.
--
Pls squash on merge, I did this from my smartphone which is why there's multiple commits 😅

docs: fix small grammar mistakes

---

docs/guide/install.md

docs: link to code

---

packages/core/package.json
packages/shiki/package.json

Export `package.json`, add exports filed of `package.json`.
Can't find `shiki/package.json`, `@shikijs/core/package.json` in Node.js.
#639

chore(core,shiki): add package.json export

---

packages/monaco/src/index.ts

fix(monaco): typo on interface

---

docs/packages/transformers.md

https://github.com/shikijs/shiki/issues/643

docs: fix inconsistence in @shikijs/transformers

---

packages/core/src/oniguruma/index.ts

Resolves https://github.com/shikijs/shiki/issues/664

fix(core): check existance of `Buffer.isBuffer`, fix #664

---

packages/vitepress-twoslash/src/index.ts

feat(vitepress-twoslash): add vueCompilerOptions

---

docs/guide/install.md

`codeToHast` is the same as the others, the return is a Promise, here in the sample code also need to use await to get the expected results
first pr submission ：）

docs: example typo

---

packages/core/src/internal.ts
packages/core/src/registry.ts
packages/core/src/types/highlighter.ts
packages/shiki/test/core.test.ts

fix https://github.com/shikijs/shiki/issues/706
This also provides a way to address the memory leak issue if multiple instances are really a desire feature.

feat(core): expose `dispose` function

---

docs/.vitepress/config.ts
docs/packages/transformers.md
packages/transformers/src/index.ts
packages/transformers/src/transformers/remove-notation-escape.ts

fixes #690 
Extracted the technique used in docs as it is and shipped it as a transformer
#690

feat: remove notation escape

---

packages/vitepress-twoslash/package.json

https://github.com/unjs/unplugin/blob/e2b9ca18e56889c51be7c609806a9ad0a3eda6ad/docs/.vitepress/theme/index.ts#L18-L19

fix(vitepress-twoslash): correct client types

---

packages/core/src/code-to-tokens.ts
packages/shiki/test/color-replacement.test.ts

fix(core): fix the incorrect parameter when using a single theme

---

docs/.vitepress/config.ts
docs/packages/next.md

Add Next.js integration guide for Shiki.
Tested the examples on CodeSandbox, should work on Next.js 14.
#754

docs: add next.js integration guide

---

docs/guide/sync-usage.md

`shiki/core` entry does not include any themes or languages

docs: update import path for langs and themes

---

packages/markdown-it/package.json
packages/rehype/package.json
pnpm-lock.yaml

It looks like `@shikijs/transformers` is only used in tests, so we could probably move it as a dev dep

chore: move `@shikijs/transformers` as dev dependency

---

docs/guide/dual-themes.md

PR adds a little bit more descriptive guide on how to style code blocks using multiple themes setup
https://github.com/shikijs/shiki/issues/800

docs: add more descriptive multiple themes example

---

docs/packages/next.md

Update import in the example docs

Use correct method in docs example

---

docs/blog/v2.md

Added "Automated Migration" before "Deprecations" (so user will see it immediately before making manual changes) with a link to [list of codemods](https://covolute.com/registry/shiki/v1-to-v2) and CLI command that run those in a sequence `npx covolute@latest shiki/v1-to-v2`

docs: add v1 to v2 automated migration link + cli command

---

packages/core/src/constructors/bundle-factory.ts
packages/core/src/constructors/highlighter.ts
packages/core/src/highlight/code-to-tokens-base.ts
packages/core/src/textmate/registry.ts
packages/shiki/src/bundle-full.ts
packages/shiki/src/bundle-web.ts
packages/shiki/src/guess.ts
packages/shiki/test/out/shorthand-markdown1.html
packages/shiki/test/out/shorthand-markdown2.html
packages/shiki/test/shorthands-markdown.test.ts
packages/types/src/highlighter.ts
pnpm-lock.yaml
pnpm-workspace.yaml

fix for https://github.com/vuejs/vitepress/pull/4564

feat(shortcuts): guess embedded language and auto load in shortcuts

---

docs/blog/v3.md

This PR adds `@shikijs/types` in `resolutions` example of v3 version guide.
None.
None.

docs: add `@shikijs/types` in version guide

---

packages/transformers/src/shared/notation-transformer.ts

fix a wrong jsdoc default value. It should have been contained in https://github.com/shikijs/shiki/pull/900

fix(transformers): fix wrong jsdoc

---

docs/packages/vitepress.md

I was installing the package in my project and I noted that the highlight is not quite correct.

docs: highlight TwoslashFloatingVue line

---

docs/.vitepress/components/HomeDemo.vue

desc:
delete the min-height of the home page demo
before: 
after:

docs: delete the min-height of the home page demo

---

docs/.vitepress/store/playground.ts
docs/.vitepress/theme/transformers.css
docs/packages/transformers.md
packages/vitepress-twoslash/src/renderer-floating-vue.ts
packages/vitepress-twoslash/test/out/completion-end-multifile-2.ts.json
packages/vitepress-twoslash/test/out/completion-end-multifile.ts.json
packages/vitepress-twoslash/test/out/completion-end.ts.json
packages/vitepress-twoslash/test/out/completion-string.ts.json
packages/vitepress-twoslash/test/out/highlights.ts.json
packages/vitepress-twoslash/test/out/import-vue.ts.json
packages/vitepress-twoslash/test/out/query-offset.ts.json

the removal of vp-code class in [vitepress@2.0.0-alpha.5](https://github.com/vuejs/vitepress/blob/main/CHANGELOG.md#breaking-changes)  and fixes the word highlighting issue #1016 
fix #1016

fix: update styling for removed vp-code class and fix word highlighting

---

docs/guide/install.md
docs/packages/cli.md
docs/packages/colorized-brackets.md
docs/packages/markdown-it.md
docs/packages/monaco.md
docs/packages/rehype.md
docs/packages/transformers.md
docs/packages/twoslash.md
docs/packages/vitepress.md

Add commands for [`deno`](https://deno.land/)
None

add commands for `deno` 

---

docs/guide/transformers.md
packages/core/src/highlight/_get-transformers.ts
packages/types/src/transformers.ts

- Allow to enforcing transformer ordering by `pre` of `post`
- Updated `Transformers` doc

feat: add `enforce` options to `ShikiTransformer`

---

.github/workflows/ci.yml

revert f66ddc7cf684b470c53656861bcf5e5a01020b4d

ci: use oidc for codecov

---

docs/packages/monaco.md

Add [modern-monaco](https://github.com/esm-dev/modern-monaco?tab=readme-ov-file#modern-monaco) usage.

doc: Update monaco integration docs
